### ISSUE TITLE
Tests naming, & running tests with nose.

### ISSUE THREAD

**Issue by baevpetr** [emissions-api/sentinel5dl#60]
During running tests encountered a problem:
1) Have to manually install nose in virtualenv:
2) Deactivate
3) Activate again
4) Rename test files because nose collector just doesn't see them at all
5) Run tests
*If you need to run them from the CLIor in some CI. In pycharm everything runs normally.
===
*Add nose & collector in setup.py\requirements.txt ?

**Comment by lkiesow** [comment]
`nose` is just a package extending Python's `unittest` package to add more functionality. For `sentinel5dl`, it's not in the requirements since you do not need to install it as we don't use it. To execute all tests, you can simply run:

    % python -m tests

In addition to that, on the CI, we also generate test coverage reports using `coverage` as an additional, optional external component:

    % coverage run --source=sentinel5dl -m tests
